export const TAURI_COMMANDS = {
  authorizeImageAsset: 'authorize_image_asset',
  fetchFontData: 'fetch_font_data',
  fetchRemoteImage: 'fetch_remote_image',
  getCachedFontPath: 'get_cached_font_path',
  importDocumentImage: 'import_document_image',
  newEditorWindow: 'new_editor_window',
  openDocument: 'open_document',
  printDocument: 'print_document',
  refreshNativeMenuShortcuts: 'refresh_native_menu_shortcuts',
  renameFile: 'rename_file',
  registerShellNew: 'register_shell_new',
  resolveDocumentImagePath: 'resolve_document_image_path',
  revealInFinder: 'reveal_in_finder',
  exitApp: 'exit_app',
  revealStartupOpenLog: 'reveal_startup_open_log',
  saveCachedFont: 'save_font_cache',
  saveClipboardImage: 'save_clipboard_image',
  saveDocument: 'save_document',
  setWindowBackgroundColor: 'set_window_background_color',
  startupReady: 'startup_ready',
  unregisterShellNew: 'unregister_shell_new',
} as const;

export type TauriCommandName = (typeof TAURI_COMMANDS)[keyof typeof TAURI_COMMANDS];
